# Tema ve dil
theme: jekyll-theme-chirpy
lang: tr
timezone: Europe/Oslo

# Site başlığı ve açıklama
title: "Ahmet Doğan"
tagline: "Yazılım, felsefe, fotoğraf ve yapay zeka üzerine yazılar"
description: "Araştırmacı, programcı ve düşünce meraklısı."

# Alan adın
url: "https://adogannw.github.io"
baseurl: ""   # ana alan, alt klasör kullanmıyorsan boş kalsın

avatar: /assets/images/profil.jpg

# Yazar bilgileri, sol panelde ve yazı meta bilgisinde görünür
author:
  name: "Ahmet Doğan"
  bio: "Araştırmacı, programcı ve düşünce meraklısı"
  location: "Drammen, Norveç"
  email: "adogannw@gmail.com"

# Sosyal bağlantılar, alt kısım ve profil için
github:
  username: adogannw

social:
  name: "Ahmet Doğan"
  email: "adogannw@gmail.com"
  links:
    - https://github.com/adogannw
    - https://instagram.com/ahmetdogankg
    - https://facebook.com/adogankg
    - mailto:adogannw@gmail.com
    - /feed.xml

# Tema modu ve içerik davranışı
theme_mode: auto       # light ya da dark da yazabilirsin
toc: true              # yazılarda içindekiler tablosu
paginate: 10           # sayfa başına yazı adedi

# Yorum sistemi, şimdilik kapalı; giscus eklemek istersen burayı doldururuz
comments:
  provider:

# Sekmeler koleksiyonu ve varsayılanlar, Chirpy'nin beklediği en yalın yapı
collections:
  tabs:
    output: true
    sort_by: order

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: true
      toc: true
      permalink: /posts/:title/
  - scope:
      path: ""
      type: tabs
    values:
      layout: page
      permalink: /:title/

# Kategori ve etiket arşivlerinin yolları
jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    category: /categories/:name/
    tag: /tags/:name/

# PWA açık kalsın, çevrimdışı önbellekleme için faydalı
pwa:
  enabled: true
  cache:
    enabled: true
